version: '3.8'

services:
  postgres-poc: # Nombre de servicio distinto
    image: postgres:15-alpine
    container_name: course-builder-db-poc
    ports:
      - "5433:5432" # Puerto 5433 en tu PC mapea al 5432 interno
    environment:
      POSTGRES_USER: user_poc
      POSTGRES_PASSWORD: password_poc
      POSTGRES_DB: course_builder_poc
    volumes:
      - postgres_data_poc:/var/lib/postgresql/data

  redis-poc:
    image: redis:7-alpine
    container_name: course-builder-redis-poc
    ports:
      - "6380:6379"

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8005:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local

volumes:
  postgres_data_poc: # Volumen aislado